version: '2'
services:
    matchit-app:
        image: matchit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://matchit-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MatchIt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=matchit-elasticsearch:9300
        ports:
            - 8080:8080
    matchit-mongodb:
        extends:
            file: mongodb.yml
            service: matchit-mongodb
    matchit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: matchit-elasticsearch
